--SELECT AVG(SPEED)
--FROM PC;

--SELECT AVG(SPEED)
--FROM LAPTOP
--WHERE PRICE >= 2500;

--SELECT AVG(PRICE)
--FROM PC
--WHERE MODEL IN (
--    SELECT MODEL
--    FROM PRODUCTS
--    WHERE MAKER = 'A'
--    );

--SELECT AVG(PRICE)
--FROM (
--    SELECT PRICE
--    FROM PC 
--    WHERE MODEL IN (
--        SELECT MODEL
--        FROM PRODUCTS
--        WHERE MAKER = 'D'
--        )
--    UNION
--    SELECT PRICE
--    FROM LAPTOP 
--    WHERE MODEL IN (
--        SELECT MODEL
--        FROM PRODUCTS
--        WHERE MAKER = 'D'
--        )
--);

--SELECT SPEED, AVG(PRICE)
--FROM PC
--GROUP BY SPEED;

--SELECT PRODUCTS.MAKER, AVG(SCREEN)
--FROM LAPTOP, PRODUCTS
--WHERE LAPTOP.MODEL = PRODUCTS.MODEL
--GROUP BY PRODUCTS.MAKER;

SELECT PRODUCTS.MAKER, COUNT(*)
FROM PRODUCTS, PC
WHERE PRODUCTS
    
    
    